# Generated by Django 2.1 on 2018-12-27 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20181221_0151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('сan_take_order_or_deliver', 'Может взять заказ или доставить')]},
        ),
        migrations.AlterField(
            model_name='orderfoods',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f', to='webapp.Food', verbose_name='Блюдо'),
        ),
    ]
