# Generated by Django 2.1 on 2018-12-27 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20181227_0511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('сan_take_order_or_deliver', 'Может взять заказ или доставить'), ('edit_order_food', 'Доступ для редактированния заказов и блюд')]},
        ),
    ]
